---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: example-kubernetes-app-mysql-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-kubernetes-app-mysql-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem  # Filesystem（文件系统） Block（块）
  accessModes:
    - ReadWriteOnce       # 卷可以被一个节点以读写方式挂载
  persistentVolumeReclaimPolicy: Delete
  storageClassName: example-kubernetes-app-mysql-storage
  local:
    path: /Users/toquery/data/mysql-data
  nodeAffinity:
    required:
      # 通过 hostname 限定在某个节点创建存储卷
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-kubernetes-app-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: example-kubernetes-app-mysql-storage
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: example-kubernetes-app-mysql-secret
type: Opaque
data:
  database-root-password: MTIzNDU2 # 123456

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-kubernetes-app-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0.28
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: example-kubernetes-app-mysql-secret
                  key: database-root-password
          ports:
            - containerPort: 3306
              protocol: TCP
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: example-kubernetes-app-mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: example-kubernetes-app-mysql
spec:
  type: ClusterIP
  clusterIP: None # headless
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      name: mysql
  selector:
    app: example-kubernetes-app-mysql
