---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: example-kubernetes-app-postgres-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-kubernetes-app-postgres-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem  # Filesystem（文件系统） Block（块）
  accessModes:
    - ReadWriteOnce       # 卷可以被一个节点以读写方式挂载
  persistentVolumeReclaimPolicy: Delete
  storageClassName: example-kubernetes-app-postgres-storage
  local:
    path: /Users/toquery/data/postgres-data
  nodeAffinity:
    required:
      # 通过 hostname 限定在某个节点创建存储卷
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-kubernetes-app-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: example-kubernetes-app-postgres-storage
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: example-kubernetes-app-postgres-secret
type: Opaque
data:
  postgres-db: cG9zdGdyZXM= # postgres
  postgres-user: cG9zdGdyZXM= # postgres
  postgres-password: MTIzNDU2 # 123456

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-kubernetes-app-postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:9.6.24
          name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: example-kubernetes-app-postgres-secret
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: example-kubernetes-app-postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: example-kubernetes-app-postgres-secret
                  key: postgres-password
          ports:
            - containerPort: 5432
              protocol: TCP
              name: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: example-kubernetes-app-postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: example-kubernetes-app-postgres
spec:
  clusterIP: None # headless
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      name: postgres
  selector:
    app: example-kubernetes-app-postgres
  type: ClusterIP
